language: objective-c
osx_image: xcode9.3

xcode_sdk:
- iphonesimulator11.3

xcode_workspace: ScrollWeaver.xcworkspace

jobs:
  include:
    - script: xcodebuild -workspace ScrollWeaver.xcworkspace -scheme ScrollWeaver -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' test

after_success:
  - bash <(curl -s https://codecov.io/bash)
